version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: christmas-tree-frontend:latest
    container_name: christmas-tree-frontend
    ports:
      - "8080:80"
    volumes:
      - /opt/christmas-tree/public/photos:/usr/share/nginx/html/photos:ro
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: christmas-tree-backend:latest
    container_name: christmas-tree-backend
    environment:
      - NODE_ENV=production
    volumes:
      - /opt/christmas-tree/public/photos:/app/public/photos
    ports:
      - "3001:3001"
    restart: unless-stopped